title: <p align="center"> Manoj Sharma </p>
logo: /assets/Photo.jpg

description: 
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a>
  <a href="https://www.linkedin.com/in/manoj-kumar-sharma-175192a/"LinkedIn</a>
  <a href="https://github.com/ms241g">GitHub</a>
  
  <br>
  Experience in executing full life-cycle development projects, ramping up projects within time, 
  budget & quality parameters, as per project management & best practice guidelines, 
  targeting assignments in Data Science, Machine Learning and Deep Learning with an 
  organization of high repute
  <br>
  </p>
  
  
  
theme: jekyll-theme-minimal
